### PR TITLE
reduce indents and return fast

### PR DESCRIPTION
**Pull request by hans2103**

### CODE REVIEW

**Comment by nayemmajhar** [comment]
Could you explain the benefits?

**Comment by hans2103** [comment]
please walk through the slideshare presentation of @Rdohms given at #JAB14 and learn how to write code that lasts. 
http://www.slideshare.net/rdohms/writing-code-that-lasts-jab14/21-Improve_codemake_it_easier_to

it's very interesting to see how code can be improved by simple rules like return fast and reduce indents.

**Comment by drbeat** [comment]
its a matter of preference but since there is huge if-block returning fast is good option to make the code simple

**Comment by nayemmajhar** [comment]
The codes are way better. If you want to contribute, you should review all code in templates. Then we can rethink about. Thanks for your contribution.

**Pull request closed without merging**
