### PR TITLE
load lessc conditional

### PR DESCRIPTION
**Pull request by 810**
- Code style
- Real code fix line 739

### CODE REVIEW

**Comment by 810** [comment]
Next issue:

The error was detected in the Shaper Helix3 Template.

 Fatal Error: Call to a member function setLessVariables() on a non-object in templates/shaper_helix3/index.php on line 132

**Comment by 810** [comment]
You have now a regression on the template:
is suggest to do this also.

But the Variables aren't loaded, so you lost the custom css.
I think you should paste them in a custom less file, and save them as css. And add it on the template.

````
if (!class_exists('lessc'))
	{
		$this->helix3->addCSS('bootstrap.min.css, font-awesome.min.css')// CSS Files
		->addJS('bootstrap.min.js, jquery.sticky.js, main.js')// JS Files
		->lessInit()->setLessVariables(array(
			'preset'      => $this->helix3->Preset(),
			'bg_color'    => $this->helix3->PresetParam('_bg'),
			'text_color'  => $this->helix3->PresetParam('_text'),
			'major_color' => $this->helix3->PresetParam('_major')
		))
			->addLess('legacy/bootstrap', 'legacy')
			->addLess('master', 'template');
	}
	else
	{
		$this->helix3->addCSS('bootstrap.min.css, font-awesome.min.css, template.css')
			->addJS('bootstrap.min.js, jquery.sticky.js, main.js');
	}
````

**Comment by nayemmajhar** [comment]
Thats nice idea. But its still pretty good. Helix3 drop out only plugins facilities and it comes with a template. So i think custom files will not disappear. custom developer will anything what they want.

Thanks

**Comment by 810** [comment]
HI, I said this because you can't use our component now. you get the follow error:
Fatal Error: Call to a member function setLessVariables() on a non-object in templates/shaper_helix3/index.php on line 132

If you could check it also.

Try to install kunena and download the Bootstrap 3 template on the download page:

issue:
http://www.kunena.org/forum/k-4-0-installation-and-upgrade/133832-crypsis-template-bugged?start=20#165961

**Comment by nayemmajhar** [comment]
ohh, got it. I will check later. Thanks again.

**Pull request merged**
